import 'package:ecom/constants.dart';

class ProductModel {
  final String image, brand, highlightHeading, name, vendorId, vendorName, pId;
  final double mrp;
  final double? priceAfetDiscount, productRatings;
  final int? dicountpercent;
  final List? reviews, variations;

  ProductModel({
    required this.image,
    required this.pId,
    required this.reviews,
    required this.variations,
    required this.vendorId,
    required this.vendorName,
    required this.brand,
    required this.productRatings,
    required this.name,
    required this.highlightHeading,
    required this.mrp,
    this.priceAfetDiscount,
    this.dicountpercent,
  });
}

List<ProductModel> demoPopularProducts = [
  ProductModel(
    variations: [],
    name: "",
    image: productDemoImg1,
    highlightHeading: "Mountain Warehouse for Women",
    brand: "Lipsy london",
    vendorId: "",
    vendorName: "",
    productRatings: 4.5,
    reviews: [],
    pId: "",
    mrp: 540,
    priceAfetDiscount: 420,
    dicountpercent: 20,
  ),
  ProductModel(
    variations: [],
    name: "",
    image: productDemoImg4,
    highlightHeading: "Mountain Beta Warehouse",
    brand: "Lipsy london",
    vendorId: "",
    vendorName: "",
    productRatings: 4.0,
    reviews: [],
    pId: "",
    mrp: 800,
  ),
  ProductModel(
    variations: [],
    name: "",
    image: productDemoImg5,
    highlightHeading: "FS - Nike Air Max 270 Really React",
    brand: "Lipsy london",
    vendorId: "",
    vendorName: "",
    productRatings: 4.8,
    reviews: [],
    pId: "",
    mrp: 650.62,
    priceAfetDiscount: 390.36,
    dicountpercent: 40,
  ),
  ProductModel(
    name: "",
    image: productDemoImg6,
    highlightHeading: "Green Poplin Ruched Front",
    brand: "Lipsy london",
    vendorId: "",
    vendorName: "",
    productRatings: 4.3,
    reviews: [],
    pId: "",
    variations: [],
    mrp: 1264,
    priceAfetDiscount: 1200.8,
    dicountpercent: 5,
  ),
  ProductModel(
    name: "",
    image: "https://i.imgur.com/tXyOMMG.png",
    highlightHeading: "Green Poplin Ruched Front",
    brand: "Lipsy london",
    vendorId: "",
    vendorName: "",
    productRatings: 4.4,
    reviews: [],
    pId: "",
    variations: [],
    mrp: 650.62,
    priceAfetDiscount: 390.36,
    dicountpercent: 40,
  ),
  ProductModel(
    name: "",
    image: "https://i.imgur.com/h2LqppX.png",
    highlightHeading: "white satin corset top",
    brand: "Lipsy london",
    vendorId: "",
    vendorName: "",
    productRatings: 4.1,
    reviews: [],
    pId: "",
    variations: [],
    mrp: 1264,
    priceAfetDiscount: 1200.8,
    dicountpercent: 5,
  ),
];

List<ProductModel> demoFlashSaleProducts = [
  ProductModel(
    name: "",
    image: productDemoImg5,
    highlightHeading: "FS - Nike Air Max 270 Really React",
    brand: "Lipsy london",
    vendorId: "",
    vendorName: "",
    productRatings: 4.8,
    reviews: [],
    pId: "",
    variations: [],
    mrp: 650.62,
    priceAfetDiscount: 390.36,
    dicountpercent: 40,
  ),
  ProductModel(
    name: "",
    image: productDemoImg6,
    highlightHeading: "Green Poplin Ruched Front",
    brand: "Lipsy london",
    vendorId: "",
    vendorName: "",
    productRatings: 4.3,
    reviews: [],
    pId: "",
    variations: [],
    mrp: 1264,
    priceAfetDiscount: 1200.8,
    dicountpercent: 5,
  ),
  ProductModel(
    name: "",
    image: productDemoImg4,
    highlightHeading: "Mountain Beta Warehouse",
    brand: "Lipsy london",
    vendorId: "",
    vendorName: "",
    productRatings: 4.0,
    reviews: [],
    pId: "",
    variations: [],
    mrp: 800,
    priceAfetDiscount: 680,
    dicountpercent: 15,
  ),
];

List<ProductModel> demoBestSellersProducts = [
  ProductModel(
    name: "",
    image: "https://i.imgur.com/tXyOMMG.png",
    highlightHeading: "Green Poplin Ruched Front",
    brand: "Lipsy london",
    vendorId: "",
    vendorName: "",
    productRatings: 4.6,
    reviews: [],
    pId: "",
    variations: [],
    mrp: 650.62,
    priceAfetDiscount: 390.36,
    dicountpercent: 40,
  ),
  ProductModel(
    name: "",
    image: "https://i.imgur.com/h2LqppX.png",
    highlightHeading: "white satin corset top",
    brand: "Lipsy london",
    vendorId: "",
    vendorName: "",
    productRatings: 4.2,
    reviews: [],
    pId: "",
    variations: [],
    mrp: 1264,
    priceAfetDiscount: 1200.8,
    dicountpercent: 5,
  ),
  ProductModel(
    name: "",
    image: productDemoImg4,
    highlightHeading: "Mountain Beta Warehouse",
    brand: "Lipsy london",
    vendorId: "",
    vendorName: "",
    productRatings: 4.0,
    reviews: [],
    pId: "",
    variations: [],
    mrp: 800,
    priceAfetDiscount: 680,
    dicountpercent: 15,
  ),
];

List<ProductModel> kidsProducts = [
  ProductModel(
    name: "",
    image: "https://i.imgur.com/dbbT6PA.png",
    highlightHeading: "Green Poplin Ruched Front",
    brand: "Lipsy london",
    vendorId: "",
    vendorName: "",
    productRatings: 4.4,
    reviews: [],
    pId: "",
    variations: [],
    mrp: 650.62,
    priceAfetDiscount: 590.36,
    dicountpercent: 24,
  ),
  ProductModel(
    name: "",
    image: "https://i.imgur.com/7fSxC7k.png",
    highlightHeading: "Printed Sleeveless Tiered Swing Dress",
    brand: "Lipsy london",
    vendorId: "",
    vendorName: "",
    productRatings: 4.1,
    reviews: [],
    pId: "",
    variations: [],
    mrp: 650.62,
  ),
  ProductModel(
    name: "",
    image: "https://i.imgur.com/pXnYE9Q.png",
    highlightHeading: "Ruffle-Sleeve Ponte-Knit Sheath",
    brand: "Lipsy london",
    vendorId: "",
    vendorName: "",
    productRatings: 4.3,
    reviews: [],
    pId: "",
    variations: [],
    mrp: 400,
  ),
  ProductModel(
    name: "",
    image: "https://i.imgur.com/V1MXgfa.png",
    highlightHeading: "Green Mountain Beta Warehouse",
    brand: "Lipsy london",
    vendorId: "",
    vendorName: "",
    productRatings: 4.2,
    reviews: [],
    pId: "",
    variations: [],
    mrp: 400,
    priceAfetDiscount: 360,
    dicountpercent: 20,
  ),
  ProductModel(
    name: "",
    image: "https://i.imgur.com/8gvE5Ss.png",
    highlightHeading: "Printed Sleeveless Tiered Swing Dress",
    brand: "Lipsy london",
    vendorId: "",
    vendorName: "",
    productRatings: 4.0,
    reviews: [],
    pId: "",
    variations: [],
    mrp: 654,
  ),
  ProductModel(
    name: "",
    image: "https://i.imgur.com/cBvB5YB.png",
    highlightHeading: "Mountain Beta Warehouse",
    brand: "Lipsy london",
    vendorId: "",
    vendorName: "",
    productRatings: 3.9,
    reviews: [],
    pId: "",
    variations: [],
    mrp: 250,
  ),
];
